
/**
 * Contains the styles names for the css.
 */
const styles = {
    LIST: 'list',
    LIST_ELEMENT: 'resource-item',
    LIST_BUTTON: 'list-button',
    ICON_BUTTON_CLASS: 'icon-button',
    OUTER_BUTTON_CLASS: 'outer-icon-button',
    BUTTON : 'button',
    FILTER_SELECTOR: 'filter-selector',
    SELECTOR_OPTION: 'selector-option',
    DATALIST_OPTION: 'datalist-option',
    TEXT: 'text',
    PAGE_LINK: 'page-link',
    PAGE_ARROW: 'page-arrow',
    PAGE_LINK_ACTIVE: 'page-link-active',
    PAGINATION: 'pagination',
    HEADER_DIV: 'header-div',
    HEADER: 'header',
    DETAIL_HEADER: 'detail-header',
    DESCRIPTION_TEXT : 'description-text',
    BX_CLASS: 'bx',
    CALENDAR_ICON: 'bx-calendar-event',
    USER_ICON: 'bx-user',
    ROUTE_ICON: 'bx-trip',
    USERS_ICON: 'bx-group',
    SPORT_ICON: 'bx-football',
    ADD_ICON: 'bx-plus-circle',
    MAP_ICON: 'bx-map-alt',
    DETAILS: 'details',
    PAGINATION_ICONS: "pagination-icons",
    NO_RESULTS_TEXT: "text-no-results",
    LIST_PARENT: 'list-parent',
    FORM : 'form',
    USER_RANKINGS: 'user-rankings',
    RANKINGS_FORM: 'rankings-form',
    ROUTE_SEARCH: 'route-search',
    SPORT_SEARCH: 'sport-search',
    ACTIVITY_FILTER: 'activity-filter',
    SPORT_FILTER: 'sport-filter',
    ROUTE_FILTER: 'route-filter',
    SEARCH_HEADER: 'search-header',
    SEARCH_ROUTE: 'search-route',
    ADD_BUTTON_CONTAINER: 'add-button-container',
    ADD_ITEM: 'add-item',
    SEARCH_CONTAINER: 'sport-search-container',
    ADD_CONTAINER: 'add-container',
    SEARCH_AND_HEADER_DIV: 'sports-search-header-container',
    FORM_TEXT_INPUT : 'form-text-input',
    SPACER: 'spacer'
}

export default styles

