openapi: 3.0.1
info:
  description: "Api reference for Sports"
  version: "0.0.0"
  title: "Swagger Sports"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "User"
    description: "Operations about user"
  - name: "Routes"
    description: "Route management"
  - name: "Sports and Activities"
    description: "Sports and Activity management."
servers:
  - url: http://localhost:9000/api
    description: Local Server
paths:
  /users/{id}:
    get:
      tags:
        - "User"
      summary: "Get user by user ID"
      description: "Gets a user by it's identifier"
      operationId: "getUserByID"
      parameters:
        - name: "id"
          in: "path"
          description: "User's identifier. Use guestID for testing."
          required: true
          schema:
            type: "string"
          example: "guestID"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "User not found"
  /users:
    get:
      tags:
        - "User"
      summary: "Get all the users"
      description: "Gets all the users"
      operationId: "getUsers"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
    post:
      tags:
        - "User"
      summary: "Add a new user"
      description: "Adds a new user with the given name and email and returns its identifier and auth token"
      operationId: "addUser"
      requestBody:
        description: "Name and Email to attribute to the user."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreationBody"
      responses:
        "201":
          description: "A user has been sucessfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseUserCreation"
        "400":
          description: "A parameter is missing or is incorrect"
  /routes/{id}:
    get:
      tags:
        - "Routes"
      summary: "Get route by route ID"
      description: "Gets a route by it's identifier"
      operationId: "getRouteByID"
      parameters:
        - name: "id"
          in: "path"
          description: "User's identifier."
          required: true
          schema:
            type: "string"
          example: "10"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Route"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Route not found"
  /routes:
    get:
      tags:
        - "Routes"
      summary: "Get all routes"
      description: "Gets all the routes."
      operationId: "getRoutes"
      responses:
        "200":
          description: "sucessfull operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteList"
    post:
      tags:
        - "Routes"
      summary: "Add a new route"
      description: "Adds a route"
      operationId: "addRoute"
      requestBody:
        description: "start location, end location and distance to attribute to a route"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RouteCreationBody"
      responses:
        "201":
          description: "A route has been sucessfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResRouteCreation"
        "400":
          description: "A parameter is missing or is incorrect"
        "401":
          description: "Unauthenticated"
components:
  schemas:
    User:
      type: "object"
      properties:
        name:
          type: "string"
          example: "guest"
        email:
          type: "string"
          example: "guest@gmail.com"
        id:
          type: "string"
          example: "guestID"
    ResponseUserCreation:
      type: "object"
      properties:
        authToken:
          type: "string"
        id:
          type: "string"
    UserCreationBody:
      type: "object"
      properties:
        name:
          type: "string"
        email:
          type: "string"
    UsersList:
      type: "object"
      properties:
        users:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
    Route:
      type: "object"
      properties:
        id:
          type: "string"
        startLocation:
          type: "string"
          example: "Lisboa"
        endLocation:
          type: "string"
          example: "Fátima"
        distance:
          type: "number"
        user:
          type: "string"
    RouteList:
      type: "object"
      properties:
        routes:
          type: "array"
          items:
            $ref: "#/components/schemas/Route"
    RouteCreationBody:
      type: "object"
      properties:
        startLocation:
          type: "string"
          example: "Lisboa"
        endLocation:
          type: "string"
          example: "Fátima"
        distance:
          type: "number"
          example: 20.0
    ResRouteCreation:
      type: "object"
      properties:
        id:
          type: "string"
          example: "routeID"