openapi: 3.0.1
info:
  description: "Api reference for Sports"
  version: "0.0.0"
  title: "Swagger Sports"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "User"
    description: "Operations about user"
  - name: "Routes"
    description: "Route management"
  - name: "Sports"
    description: "Sports management."
  - name: "Activities"
    description: "Activity management."
servers:
  - url: http://localhost:9000/api
    description: Local Server
paths:
  /users/{id}:
    get:
      tags:
        - "User"
      summary: "Get user by user ID"
      description: "Gets a user by it's identifier"
      operationId: "getUserByID"
      parameters:
        - name: "id"
          in: "path"
          description: "User's identifier. Use guestID for testing."
          required: true
          schema:
            type: "string"
          example: "guestID"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: "User not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
  /users:
    get:
      tags:
        - "User"
      summary: "Get all the users"
      description: "Gets all the users"
      operationId: "getUsers"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"
    post:
      tags:
        - "User"
      summary: "Add a new user"
      description: "Adds a new user with the given name and email and returns its identifier and auth token"
      operationId: "addUser"
      requestBody:
        description: "Name and Email to attribute to the user."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreationBody"
      responses:
        "201":
          description: "A user has been sucessfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreationResponse"
        "400":
          description: "A parameter is missing or is incorrect"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
  /routes/{id}:
    get:
      tags:
        - "Routes"
      summary: "Get route by route ID"
      description: "Gets a route by it's identifier"
      operationId: "getRouteByID"
      parameters:
        - name: "id"
          in: "path"
          description: "Route's identifier."
          required: true
          schema:
            type: "string"
          example: "10"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Route"
        "404":
          description: "Route not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
  /routes:
    get:
      tags:
        - "Routes"
      summary: "Get all routes"
      description: "Gets all the routes."
      operationId: "getRoutes"
      responses:
        "200":
          description: "sucessfull operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteList"
    post:
      tags:
        - "Routes"
      summary: "Add a new route"
      description: "Adds a route"
      operationId: "addRoute"
      requestBody:
        description: "start location, end location and distance to attribute to a route"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RouteCreationBody"
      responses:
        "201":
          description: "A route has been sucessfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteCreationResponse"
        "400":
          description: "A parameter is missing or is incorrect"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
        "401":
          description: "Unauthenticated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
  /sports:
    get:
      tags:
        - "Sports"
      summary: "Get all sports"
      description: "Gets all the sports."
      operationId: "getsports"
      responses:
        "200":
          description: "sucessfull operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SportList"
    post:
      tags:
        - "Sports"
      summary: "Create a sport"
      description: "Create a sport with a name and description"
      operationId: "createsport"
      requestBody:
        description: "start location, end location and distance to attribute to a route"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SportCreationBody"
      responses:
        "200":
          description: "Sport created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SportCreationResponse"
        "400":
          description: "A required parameter is missing or is incorrect"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
  /sports/{id}:
    get:
      tags:
        - "Sports"
      summary: "Get a sport"
      description: "Gets a sport by id"
      operationId: "getsport"
      parameters:
        - name: "id"
          in: "path"
          description: "Sport's identifier."
          required: true
          schema:
            type: "string"
          example: "1234154"
      responses:
        "200":
          description: "sucessfull operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sport"
        "404":
          description: "Sport not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpError"
components:
  schemas:
    HttpError:
      type: "object"
      properties:
        code:
          type: "int"
          example: 2000
        message:
          type: "string"
          example: "Invalid parameter: email"
    User:
      type: "object"
      properties:
        name:
          type: "string"
          example: "guest"
        email:
          type: "string"
          example: "guest@gmail.com"
        id:
          type: "string"
          example: "guestID"
    UserList:
      type: "object"
      properties:
        users:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
    UserCreationBody:
      type: "object"
      properties:
        name:
          type: "string"
        email:
          type: "string"
    UserCreationResponse:
      type: "object"
      properties:
        authToken:
          type: "string"
        id:
          type: "string"
    Route:
      type: "object"
      properties:
        id:
          type: "string"
        startLocation:
          type: "string"
          example: "Lisboa"
        endLocation:
          type: "string"
          example: "Fátima"
        distance:
          type: "number"
        user:
          type: "string"
    RouteList:
      type: "object"
      properties:
        routes:
          type: "array"
          items:
            $ref: "#/components/schemas/Route"
    RouteCreationBody:
      type: "object"
      properties:
        startLocation:
          type: "string"
          example: "Lisboa"
        endLocation:
          type: "string"
          example: "Fátima"
        distance:
          type: "number"
          example: 128.7
    RouteCreationResponse:
      type: "object"
      properties:
        id:
          type: "string"
          example: "routeID"
    Sport:
      type: "object"
      required:
        - id
        - name
        - user
      properties:
        id:
          type: "string"
          example: "sportID"
        name:
          type: "string"
          example: "Football"
        description:
          type: "string"
          example: "Game played with feet."
        user:
          type: "string"
          example: "guestID"
    SportList:
      type: "object"
      properties:
        sports:
          type: "array"
          items:
            $ref: "#/components/schemas/Sport"
    SportCreationBody:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
          example: "Football"
        description:
          type: "string"
          example: "Game played with feet."
    SportCreationResponse:
      type: "object"
      properties:
        sportID:
          type: "string"
          example: "123141245"
